### ISSUE TITLE
Todo: Implement Hunt menu

### ISSUE THREAD

**Issue by Rexhunter99** [carnivores-cpe/Carn2-Menu#4]
Hunt menu is bare bones, has basic rendering of text UI.

- Need to implement thumbnail/picture rendering
- Loading of text elements as required
- Rendering of toggle-able buttons
- Calculate cost of all chosen items, subtract from total score available and display at top on right.
- Suggestion: Scroll-able text lists

**Comment by tminard** [comment]
+1 on scrollable lists

**Comment by Rexhunter99** [comment]
> +1 on scrollable lists

Areas and dinosaurs are capable of being scrolled with the scroll-wheel. I will later on implement a slider bar that acts like a scroll bar.  The menu supports 'unlimited' amounts of maps and up to 32 huntable creatures. Though that requires source-code modders to implement support in their .REN builds.

**Comment by Rexhunter99** [comment]
All that's left of the Hunt menu now is configuring the Info part of the screen to show dinosaur, weapon and accessory information, right now it only shows areas. It also needs to be adjusted so that it displays synchronised with the thumbnail (right now it doesn't, it works via last clicked.)
